import { Project, ProjectStatus, Role } from 'utils/types';

export const PROJECTS: Project[] = [
   {
      id: 1,
      name: 'Project 1',
      status: ProjectStatus.InProgress,
      client: 'ZinZa. Co',
      description: 'Lorem Ipsum is simply dummy text',
      startDate: '2021-09-27',
      endDate: '2021-11-02',
      members: [
         {
            id: 5,
            username: 'member1',
            password: '123456',
            firstName: 'Bùi',
            lastName: 'Hoàng',
            email: 'hellozinza5@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: false,
         },
         {
            id: 6,
            username: 'member2',
            password: '123456',
            firstName: 'Nguyễn',
            lastName: 'Hà',
            email: 'hellozinza6@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: true,
         },
         {
            id: 7,
            username: 'member3',
            password: '123456',
            firstName: 'Đinh',
            lastName: 'Nam',
            email: 'hellozinza7@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: true,
         },
      ],
      pm: {
         id: 2,
         username: 'projectmanager',
         password: '123456',
         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         active: true,
      },
   },
   {
      id: 2,
      name: 'Project 2',
      status: ProjectStatus.Completed,
      client: 'ZinZa. Co',
      description: 'Lorem Ipsum is simply dummy text',
      startDate: '2021-09-27',
      endDate: '2021-11-02',
      members: [
         {
            id: 6,
            username: 'member2',
            password: '123456',
            firstName: 'Nguyễn',
            lastName: 'Hà',
            email: 'hellozinza6@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: true,
         },
         {
            id: 7,
            username: 'member3',
            password: '123456',
            firstName: 'Đinh',
            lastName: 'Nam',
            email: 'hellozinza7@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: true,
         },
         {
            id: 8,
            username: 'member8',
            password: '123456',
            firstName: 'Trần',
            lastName: 'Hiếu',
            email: 'hellozinza8@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: true,
         },
      ],
      pm: {
         id: 4,
         username: 'projectmanager3',
         password: '123456',
         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         active: true,
      },
   },
   {
      id: 3,
      name: 'Project 3',
      status: ProjectStatus.Completed,
      client: 'ZinZa. Co',
      description: 'Lorem Ipsum is simply dummy text',
      startDate: '2021-09-27',
      endDate: '2021-10-27',
      members: [
         {
            id: 8,
            username: 'member8',
            password: '123456',
            firstName: 'Trần',
            lastName: 'Hiếu',
            email: 'hellozinza8@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: true,
         },
         {
            id: 9,
            username: 'member9',
            password: '123456',
            firstName: 'Bùi',
            lastName: 'Duy',
            email: 'hellozinza9@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: true,
         },
         {
            id: 5,
            username: 'member1',
            password: '123456',
            firstName: 'Bùi',
            lastName: 'Hoàng',
            email: 'hellozinza5@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: false,
         },
      ],
      pm: {
         id: 3,
         username: 'projectmanager2',
         password: '123456',
         firstName: 'Duy',
         lastName: 'Hà',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '2000-04-19',
         role: Role.Member,
         active: true,
      },
   },
   {
      id: 4,
      name: 'Project 4',
      status: ProjectStatus.Completed,
      client: 'ZinZa. Co',
      description: 'Lorem Ipsum is simply dummy text',
      startDate: '2021-09-27',
      endDate: '2021-10-27',
      members: [
         {
            id: 4,
            username: 'projectmanager3',
            password: '123456',
            firstName: 'Lại',
            lastName: 'Lan',
            email: 'hellozinza4@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.PM,
            active: true,
         },
         {
            id: 5,
            username: 'member1',
            password: '123456',
            firstName: 'Bùi',
            lastName: 'Hoàng',
            email: 'hellozinza5@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: false,
         },
         {
            id: 6,
            username: 'member2',
            password: '123456',
            firstName: 'Nguyễn',
            lastName: 'Hà',
            email: 'hellozinza6@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: true,
         },
         {
            id: 7,
            username: 'member3',
            password: '123456',
            firstName: 'Đinh',
            lastName: 'Nam',
            email: 'hellozinza7@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: true,
         },
      ],
      pm: {
         id: 2,
         username: 'projectmanager',
         password: '123456',
         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         active: true,
      },
   },
   {
      id: 5,
      name: 'Project 5',
      status: ProjectStatus.Completed,
      client: 'ZinZa. Co',
      description: 'Lorem Ipsum is simply dummy text',
      startDate: '2021-09-27',
      endDate: '2021-10-27',
      members: [
         {
            id: 7,
            username: 'member3',
            password: '123456',
            firstName: 'Đinh',
            lastName: 'Nam',
            email: 'hellozinza7@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: true,
         },
         {
            id: 9,
            username: 'member9',
            password: '123456',
            firstName: 'Bùi',
            lastName: 'Duy',
            email: 'hellozinza9@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: true,
         },
         {
            id: 5,
            username: 'member1',
            password: '123456',
            firstName: 'Bùi',
            lastName: 'Hoàng',
            email: 'hellozinza5@gmail.com',
            dateOfBirth: '1999-01-25',
            role: Role.Member,
            active: false,
         },
      ],
      pm: {
         id: 4,
         username: 'projectmanager3',
         password: '123456',
         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         active: true,
      },
   },
];
