import { Task, TaskStatus, TaskPriority, Role, UserStatus } from 'utils/types';

export const TASKS: Task[] = [
   {
      id: 1,
      assignTo: {
         id: 6,
         username: 'member2',
         firstName: 'Nguyễn',
         lastName: 'Hà',
         email: 'hellozinza6@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 2,
         username: 'projectmanager',

         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 1,
      title: 'Task 1',
      notes: 'Task 1 of project 1 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Cancelled,
      priority: TaskPriority.High,
   },
   {
      id: 2,
      assignTo: {
         id: 5,
         username: 'member1',

         firstName: 'Bùi',
         lastName: 'Hoàng',
         email: 'hellozinza5@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.inactive,
      },
      requestByUser: {
         id: 2,
         username: 'projectmanager',

         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 1,
      title: 'Task 2',
      notes: 'Task 2 of project 1 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Completed,
      priority: TaskPriority.High,
   },
   {
      id: 3,
      assignTo: {
         id: 7,
         username: 'member3',

         firstName: 'Đinh',
         lastName: 'Nam',
         email: 'hellozinza7@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 2,
         username: 'projectmanager',

         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 1,
      title: 'Task 3',
      notes: 'Task 3 of project 1 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Unscheduled,
      priority: TaskPriority.High,
   },
   {
      id: 4,
      assignTo: {
         id: 6,
         username: 'member2',

         firstName: 'Nguyễn',
         lastName: 'Hà',
         email: 'hellozinza6@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 2,
         username: 'projectmanager',

         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 1,
      title: 'Task 4',
      notes: 'Task 4 of project 1 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Unscheduled,
      priority: TaskPriority.High,
   },
   {
      id: 5,
      assignTo: {
         id: 5,
         username: 'member1',

         firstName: 'Bùi',
         lastName: 'Hoàng',
         email: 'hellozinza5@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.inactive,
      },
      requestByUser: {
         id: 2,
         username: 'projectmanager',

         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 1,
      title: 'Task 5',
      notes: 'Task 5 of project 1 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Doing,
      priority: TaskPriority.Medium,
   },
   {
      id: 6,
      assignTo: {
         id: 7,
         username: 'member3',

         firstName: 'Đinh',
         lastName: 'Nam',
         email: 'hellozinza7@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 2,
         username: 'projectmanager',

         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 1,
      title: 'Task 6',
      notes: 'Task 6 of project 1 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Unscheduled,
      priority: TaskPriority.High,
   },
   {
      id: 7,
      assignTo: {
         id: 7,
         username: 'member3',

         firstName: 'Đinh',
         lastName: 'Nam',
         email: 'hellozinza7@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 2,
         username: 'projectmanager',

         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 1,
      title: 'Task 7',
      notes: 'Task 7 of project 1 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Completed,
      priority: TaskPriority.Medium,
   },
   {
      id: 1,
      assignTo: {
         id: 6,
         username: 'member2',

         firstName: 'Nguyễn',
         lastName: 'Hà',
         email: 'hellozinza6@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 2,
      title: 'Task 1',
      notes: 'Task 1 of project 2 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Doing,
      priority: TaskPriority.Medium,
   },
   {
      id: 2,
      assignTo: {
         id: 7,
         username: 'member3',

         firstName: 'Đinh',
         lastName: 'Nam',
         email: 'hellozinza7@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 2,
      title: 'Task 2',
      notes: 'Task 2 of project 2 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Reviewing,
      priority: TaskPriority.Medium,
   },
   {
      id: 3,
      assignTo: {
         id: 6,
         username: 'member2',

         firstName: 'Nguyễn',
         lastName: 'Hà',
         email: 'hellozinza6@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 2,
      title: 'Task 3',
      notes: 'Task 3 of project 2 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Reviewing,
      priority: TaskPriority.Medium,
   },
   {
      id: 4,
      assignTo: {
         id: 6,
         username: 'member2',

         firstName: 'Nguyễn',
         lastName: 'Hà',
         email: 'hellozinza6@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 2,
      title: 'Task 4',
      notes: 'Task 4 of project 2 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Doing,
      priority: TaskPriority.High,
   },
   {
      id: 5,
      assignTo: {
         id: 6,
         username: 'member2',

         firstName: 'Nguyễn',
         lastName: 'Hà',
         email: 'hellozinza6@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 2,
      title: 'Task 5',
      notes: 'Task 5 of project 2 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Completed,
      priority: TaskPriority.Medium,
   },
   {
      id: 6,
      assignTo: {
         id: 7,
         username: 'member3',

         firstName: 'Đinh',
         lastName: 'Nam',
         email: 'hellozinza7@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 2,
      title: 'Task 6',
      notes: 'Task 6 of project 2 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Cancelled,
      priority: TaskPriority.Medium,
   },
   {
      id: 7,
      assignTo: {
         id: 8,
         username: 'member8',

         firstName: 'Trần',
         lastName: 'Hiếu',
         email: 'hellozinza8@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 2,
      title: 'Task 7',
      notes: 'Task 7 of project 2 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Completed,
      priority: TaskPriority.Medium,
   },
   {
      id: 1,
      assignTo: {
         id: 5,
         username: 'member1',

         firstName: 'Bùi',
         lastName: 'Hoàng',
         email: 'hellozinza5@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.inactive,
      },
      requestByUser: {
         id: 3,
         username: 'projectmanager2',

         firstName: 'Duy',
         lastName: 'Hà',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '2000-04-19',
         role: Role.Member,
         status: UserStatus.active,
      },
      projectId: 3,
      title: 'Task 1',
      notes: 'Task 1 of project 3 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Completed,
      priority: TaskPriority.High,
   },
   {
      id: 2,
      assignTo: {
         id: 9,
         username: 'member9',

         firstName: 'Bùi',
         lastName: 'Duy',
         email: 'hellozinza9@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 3,
         username: 'projectmanager2',

         firstName: 'Duy',
         lastName: 'Hà',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '2000-04-19',
         role: Role.Member,
         status: UserStatus.active,
      },
      projectId: 3,
      title: 'Task 2',
      notes: 'Task 2 of project 3 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Reviewing,
      priority: TaskPriority.High,
   },
   {
      id: 3,
      assignTo: {
         id: 8,
         username: 'member8',

         firstName: 'Trần',
         lastName: 'Hiếu',
         email: 'hellozinza8@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 3,
         username: 'projectmanager2',

         firstName: 'Duy',
         lastName: 'Hà',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '2000-04-19',
         role: Role.Member,
         status: UserStatus.active,
      },
      projectId: 3,
      title: 'Task 3',
      notes: 'Task 3 of project 3 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Cancelled,
      priority: TaskPriority.High,
   },
   {
      id: 4,
      assignTo: {
         id: 5,
         username: 'member1',

         firstName: 'Bùi',
         lastName: 'Hoàng',
         email: 'hellozinza5@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.inactive,
      },
      requestByUser: {
         id: 3,
         username: 'projectmanager2',

         firstName: 'Duy',
         lastName: 'Hà',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '2000-04-19',
         role: Role.Member,
         status: UserStatus.active,
      },
      projectId: 3,
      title: 'Task 4',
      notes: 'Task 4 of project 3 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Completed,
      priority: TaskPriority.Medium,
   },
   {
      id: 5,
      assignTo: {
         id: 8,
         username: 'member8',

         firstName: 'Trần',
         lastName: 'Hiếu',
         email: 'hellozinza8@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 3,
         username: 'projectmanager2',

         firstName: 'Duy',
         lastName: 'Hà',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '2000-04-19',
         role: Role.Member,
         status: UserStatus.active,
      },
      projectId: 3,
      title: 'Task 5',
      notes: 'Task 5 of project 3 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Unscheduled,
      priority: TaskPriority.Medium,
   },
   {
      id: 6,
      assignTo: {
         id: 9,
         username: 'member9',

         firstName: 'Bùi',
         lastName: 'Duy',
         email: 'hellozinza9@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 3,
         username: 'projectmanager2',

         firstName: 'Duy',
         lastName: 'Hà',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '2000-04-19',
         role: Role.Member,
         status: UserStatus.active,
      },
      projectId: 3,
      title: 'Task 6',
      notes: 'Task 6 of project 3 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Completed,
      priority: TaskPriority.High,
   },
   {
      id: 7,
      assignTo: {
         id: 9,
         username: 'member9',

         firstName: 'Bùi',
         lastName: 'Duy',
         email: 'hellozinza9@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 3,
         username: 'projectmanager2',

         firstName: 'Duy',
         lastName: 'Hà',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '2000-04-19',
         role: Role.Member,
         status: UserStatus.active,
      },
      projectId: 3,
      title: 'Task 7',
      notes: 'Task 7 of project 3 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Reviewing,
      priority: TaskPriority.Medium,
   },
   {
      id: 1,
      assignTo: {
         id: 5,
         username: 'member1',

         firstName: 'Bùi',
         lastName: 'Hoàng',
         email: 'hellozinza5@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.inactive,
      },
      requestByUser: {
         id: 2,
         username: 'projectmanager',

         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 4,
      title: 'Task 1',
      notes: 'Task 1 of project 4 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Cancelled,
      priority: TaskPriority.Medium,
   },
   {
      id: 2,
      assignTo: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 2,
         username: 'projectmanager',

         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 4,
      title: 'Task 2',
      notes: 'Task 2 of project 4 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Reviewing,
      priority: TaskPriority.Medium,
   },
   {
      id: 3,
      assignTo: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 2,
         username: 'projectmanager',

         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 4,
      title: 'Task 3',
      notes: 'Task 3 of project 4 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Doing,
      priority: TaskPriority.High,
   },
   {
      id: 4,
      assignTo: {
         id: 7,
         username: 'member3',

         firstName: 'Đinh',
         lastName: 'Nam',
         email: 'hellozinza7@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 2,
         username: 'projectmanager',

         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 4,
      title: 'Task 4',
      notes: 'Task 4 of project 4 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Cancelled,
      priority: TaskPriority.Medium,
   },
   {
      id: 5,
      assignTo: {
         id: 6,
         username: 'member2',

         firstName: 'Nguyễn',
         lastName: 'Hà',
         email: 'hellozinza6@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 2,
         username: 'projectmanager',

         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 4,
      title: 'Task 5',
      notes: 'Task 5 of project 4 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Doing,
      priority: TaskPriority.High,
   },
   {
      id: 6,
      assignTo: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 2,
         username: 'projectmanager',

         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 4,
      title: 'Task 6',
      notes: 'Task 6 of project 4 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Unscheduled,
      priority: TaskPriority.High,
   },
   {
      id: 7,
      assignTo: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 2,
         username: 'projectmanager',

         firstName: 'Văn',
         lastName: 'Hiệp',
         email: 'hellozinza@gmail.com',
         dateOfBirth: '1992-02-21',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 4,
      title: 'Task 7',
      notes: 'Task 7 of project 4 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Unscheduled,
      priority: TaskPriority.Medium,
   },
   {
      id: 1,
      assignTo: {
         id: 5,
         username: 'member1',

         firstName: 'Bùi',
         lastName: 'Hoàng',
         email: 'hellozinza5@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.inactive,
      },
      requestByUser: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 5,
      title: 'Task 1',
      notes: 'Task 1 of project 5 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Cancelled,
      priority: TaskPriority.High,
   },
   {
      id: 2,
      assignTo: {
         id: 5,
         username: 'member1',

         firstName: 'Bùi',
         lastName: 'Hoàng',
         email: 'hellozinza5@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.inactive,
      },
      requestByUser: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 5,
      title: 'Task 2',
      notes: 'Task 2 of project 5 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Unscheduled,
      priority: TaskPriority.Medium,
   },
   {
      id: 3,
      assignTo: {
         id: 9,
         username: 'member9',

         firstName: 'Bùi',
         lastName: 'Duy',
         email: 'hellozinza9@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 5,
      title: 'Task 3',
      notes: 'Task 3 of project 5 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Cancelled,
      priority: TaskPriority.High,
   },
   {
      id: 4,
      assignTo: {
         id: 9,
         username: 'member9',

         firstName: 'Bùi',
         lastName: 'Duy',
         email: 'hellozinza9@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 5,
      title: 'Task 4',
      notes: 'Task 4 of project 5 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Completed,
      priority: TaskPriority.High,
   },
   {
      id: 5,
      assignTo: {
         id: 5,
         username: 'member1',

         firstName: 'Bùi',
         lastName: 'Hoàng',
         email: 'hellozinza5@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.inactive,
      },
      requestByUser: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 5,
      title: 'Task 5',
      notes: 'Task 5 of project 5 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Cancelled,
      priority: TaskPriority.Medium,
   },
   {
      id: 6,
      assignTo: {
         id: 5,
         username: 'member1',

         firstName: 'Bùi',
         lastName: 'Hoàng',
         email: 'hellozinza5@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.inactive,
      },
      requestByUser: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 5,
      title: 'Task 6',
      notes: 'Task 6 of project 5 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Reviewing,
      priority: TaskPriority.Medium,
   },
   {
      id: 7,
      assignTo: {
         id: 9,
         username: 'member9',

         firstName: 'Bùi',
         lastName: 'Duy',
         email: 'hellozinza9@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.Member,
         status: UserStatus.active,
      },
      requestByUser: {
         id: 4,
         username: 'projectmanager3',

         firstName: 'Lại',
         lastName: 'Lan',
         email: 'hellozinza4@gmail.com',
         dateOfBirth: '1999-01-25',
         role: Role.PM,
         status: UserStatus.active,
      },
      projectId: 5,
      title: 'Task 7',
      notes: 'Task 7 of project 5 note',
      dueDate: '2021-10-09',
      status: TaskStatus.Reviewing,
      priority: TaskPriority.High,
   },
];
