import { User, Role, UserStatus } from 'utils/types';

export const USERS: User[] = [
   {
      id: 1,
      username: 'admin',
      password: '123456',
      firstName: 'Duy',
      lastName: 'Hiệp',
      email: 'hellozinza@gmail.com',
      dateOfBirth: '1999-01-25',
      role: Role.Admin,
      status: UserStatus.active,
   },
   {
      id: 2,
      username: 'projectmanager',
      password: '123456',
      firstName: 'Văn',
      lastName: 'Hiệp',
      email: 'hellozinza@gmail.com',
      dateOfBirth: '1992-02-21',
      role: Role.PM,
      status: UserStatus.active,
   },

   {
      id: 3,
      username: 'projectmanager2',
      password: '123456',
      firstName: 'Duy',
      lastName: 'Hà',
      email: 'hellozinza@gmail.com',
      dateOfBirth: '2000-04-19',
      role: Role.PM,
      status: UserStatus.active,
   },
   {
      id: 4,
      username: 'projectmanager3',
      password: '123456',
      firstName: 'Lại',
      lastName: 'Lan',
      email: 'hellozinza4@gmail.com',
      dateOfBirth: '1999-01-25',
      role: Role.PM,
      status: UserStatus.active,
   },
   {
      id: 5,
      username: 'member1',
      password: '123456',
      firstName: 'Bùi',
      lastName: 'Hoàng',
      email: 'hellozinza5@gmail.com',
      dateOfBirth: '1999-01-25',
      role: Role.Member,
      status: UserStatus.inactive,
   },
   {
      id: 6,
      username: 'member2',
      password: '123456',
      firstName: 'Nguyễn',
      lastName: 'Hà',
      email: 'hellozinza6@gmail.com',
      dateOfBirth: '1999-01-25',
      role: Role.Member,
      status: UserStatus.active,
   },
   {
      id: 7,
      username: 'member3',
      password: '123456',
      firstName: 'Đinh',
      lastName: 'Nam',
      email: 'hellozinza7@gmail.com',
      dateOfBirth: '1999-01-25',
      role: Role.Member,
      status: UserStatus.active,
   },
   {
      id: 8,
      username: 'member8',
      password: '123456',
      firstName: 'Trần',
      lastName: 'Hiếu',
      email: 'hellozinza8@gmail.com',
      dateOfBirth: '1999-01-25',
      role: Role.Member,
      status: UserStatus.active,
   },
   {
      id: 9,
      username: 'member9',
      password: '123456',
      firstName: 'Bùi',
      lastName: 'Duy',
      email: 'hellozinza9@gmail.com',
      dateOfBirth: '1999-01-25',
      role: Role.Member,
      status: UserStatus.active,
   },
   {
      id: 10,
      username: 'member10',
      password: '123456',
      firstName: 'Nguyễn',
      lastName: 'Mai',
      email: 'hellozinza10@gmail.com',
      dateOfBirth: '1999-01-25',
      role: Role.Member,
      status: UserStatus.active,
   },
   {
      id: 11,
      username: 'member11',
      password: '123456',
      firstName: 'Đỗ',
      lastName: 'Nam',
      email: 'hellozinza11@gmail.com',
      dateOfBirth: '1999-01-25',
      role: Role.Member,
      status: UserStatus.active,
   },
   {
      id: 12,
      username: 'member12',
      password: '123456',
      firstName: 'Bùi',
      lastName: 'Lan',
      email: 'hellozinza12@gmail.com',
      dateOfBirth: '1999-01-25',
      role: Role.Member,
      status: UserStatus.active,
   },
   {
      id: 13,
      username: 'member13',
      password: '123456',
      firstName: 'Trần',
      lastName: 'Hằng',
      email: 'hellozinza13@gmail.com',
      dateOfBirth: '1999-01-25',
      role: Role.Member,
      status: UserStatus.active,
   },
   {
      id: 14,
      username: 'member14',
      password: '123456',
      firstName: 'Đinh',
      lastName: 'Hưng',
      email: 'hellozinza14@gmail.com',
      dateOfBirth: '1999-01-25',
      role: Role.Member,
      status: UserStatus.active,
   },
   {
      id: 15,
      username: 'member15',
      password: '123456',
      firstName: 'Lại',
      lastName: 'Hiếu',
      email: 'hellozinza15@gmail.com',
      dateOfBirth: '1999-01-25',
      role: Role.Member,
      status: UserStatus.active,
   },
   {
      id: 16,
      username: 'member16',
      password: '123456',
      firstName: 'Bùi',
      lastName: 'Nam',
      email: 'hellozinza16@gmail.com',
      dateOfBirth: '1999-01-25',
      role: Role.Member,
      status: UserStatus.active,
   },
];
