import { User, Role } from 'utils/types';

export const USERS: User[] = [
   {
      id: 1,
      username: 'admin',
      password: '123456',
      fullName: 'Trần Duy Hiệp',
      email: 'hellozinza@gmail.com',
      dateOfBirth: '01/01/1993',
      roles: Role.Admin,
      active: true,
   },
   {
      id: 2,
      username: 'projectmanager',
      password: '123456',
      fullName: 'Nguyễn Văn Cảnh',
      email: 'hellozinza@gmail.com',
      dateOfBirth: '07/09/2021',
      roles: Role.PM,
      active: true,
   },
   {
      id: 3,
      username: 'member',
      password: '123456',
      fullName: 'Nguyễn Văn Hảnh',
      email: 'hellozinza@gmail.com',
      dateOfBirth: '16/09/2021',
      roles: Role.Member,
      active: true,
   },
   {
      id: 4,
      username: 'member',
      password: '123456',
      fullName: 'Bùi Thái Thọ',
      email: 'hellozinza@gmail.com',
      dateOfBirth: '16/09/2021',
      roles: Role.Member,
      active: false,
   },
   {
      id: 4,
      username: 'member',
      password: '123456',
      fullName: 'Bùi Thái Thọ',
      email: 'hellozinza@gmail.com',
      dateOfBirth: '16/09/2021',
      roles: Role.Member,
      active: false,
   },
   {
      id: 4,
      username: 'member',
      password: '123456',
      fullName: 'Hạ Thái Thọ',
      email: 'hellozinza@gmail.com',
      dateOfBirth: '17/09/2021',
      roles: Role.Member,
      active: false,
   },
   {
      id: 4,
      username: 'member',
      password: '123456',
      fullName: 'Đỗ Thái Thọ',
      email: 'hellozinza@gmail.com',
      dateOfBirth: '12/09/2021',
      roles: Role.Member,
      active: false,
   },
];
